package irrgarten.UI;
import irrgarten.Directions;

public class Cursors extends javax.swing.JDialog {
    private Directions direction;
    
    public Cursors(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UPbutton = new javax.swing.JButton();
        DOWNbutton = new javax.swing.JButton();
        LEFTbutton = new javax.swing.JButton();
        RIGHTbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setLocation(new java.awt.Point(800, 200));
        setMinimumSize(new java.awt.Dimension(200, 300));

        UPbutton.setText("UP");
        UPbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPbuttonActionPerformed(evt);
            }
        });

        DOWNbutton.setText("DOWN");
        DOWNbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOWNbuttonActionPerformed(evt);
            }
        });

        LEFTbutton.setText("LEFT");
        LEFTbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LEFTbuttonActionPerformed(evt);
            }
        });

        RIGHTbutton.setText("RIGHT");
        RIGHTbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RIGHTbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(LEFTbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(RIGHTbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DOWNbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UPbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(UPbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RIGHTbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LEFTbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(DOWNbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RIGHTbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RIGHTbuttonActionPerformed
        this.direction  = Directions.RIGHT;
        this.dispose();
    }//GEN-LAST:event_RIGHTbuttonActionPerformed

    private void LEFTbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LEFTbuttonActionPerformed
        this.direction  = Directions.LEFT;
        this.dispose();
    }//GEN-LAST:event_LEFTbuttonActionPerformed

    private void UPbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPbuttonActionPerformed
        this.direction  = Directions.UP;
        this.dispose();
    }//GEN-LAST:event_UPbuttonActionPerformed

    private void DOWNbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOWNbuttonActionPerformed
        this.direction  = Directions.DOWN;
        this.dispose();
    }//GEN-LAST:event_DOWNbuttonActionPerformed

    public Directions getDirection(){
        this.setVisible(true);
        return this.direction;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DOWNbutton;
    private javax.swing.JButton LEFTbutton;
    private javax.swing.JButton RIGHTbutton;
    private javax.swing.JButton UPbutton;
    // End of variables declaration//GEN-END:variables
}
