package irrgarten.UI;
import irrgarten.Directions;
import irrgarten.GameState;

public class GraphicalUI extends javax.swing.JFrame implements UI{

    private Cursors cursor;
    
    public GraphicalUI() {
        initComponents();
        this.cursor = new Cursors(this,true);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Labyrinth = new javax.swing.JTextArea();
        currentPlayerField = new javax.swing.JTextField();
        winnerField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        logField = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        playersField = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        monstersField = new javax.swing.JTextArea();
        monstersLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(110, 60));

        Labyrinth.setEditable(false);
        Labyrinth.setColumns(20);
        Labyrinth.setRows(5);
        jScrollPane1.setViewportView(Labyrinth);

        currentPlayerLabel.setText("Current Player: ");

        winnerLabel.setText("Winner ?: ");

        currentPlayerField.setEditable(false);
        currentPlayerField.setText("jTextField1");
        currentPlayerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentPlayerFieldActionPerformed(evt);
            }
        });

        winnerField.setEditable(false);
        winnerField.setText("jTextField2");

        logField.setEditable(false);
        logField.setColumns(20);
        logField.setRows(5);
        jScrollPane2.setViewportView(logField);

        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        playersField.setEditable(false);
        playersField.setColumns(20);
        playersField.setRows(5);
        jScrollPane3.setViewportView(playersField);

        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        monstersField.setEditable(false);
        monstersField.setColumns(20);
        monstersField.setRows(5);
        jScrollPane4.setViewportView(monstersField);

        logLabel.setText("Log: ");

        playersLabel.setText("Players: ");

        monstersLabel.setText("Monsters: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(playersLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(monstersLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(currentPlayerLabel)
                                .addGap(18, 18, 18)
                                .addComponent(currentPlayerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(winnerLabel)
                                .addGap(18, 18, 18)
                                .addComponent(winnerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                                .addComponent(jScrollPane3)
                                .addComponent(jScrollPane4)))
                        .addGap(26, 26, 26))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentPlayerLabel)
                    .addComponent(currentPlayerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(winnerLabel)
                        .addComponent(winnerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playersLabel)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(monstersLabel)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void currentPlayerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentPlayerFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentPlayerFieldActionPerformed

    @Override
    public void showGame(GameState gameState){
        this.Labyrinth.setText(gameState.getLabyrinth());
        this.winnerField.setText(Boolean.toString(gameState.getWinner()));
        this.currentPlayerField.setText(Integer.toString(gameState.getCurrentPlayer()));
        this.logField.setText(gameState.getLog());
        this.playersField.setText(gameState.getPlayers());
        this.monstersField.setText(gameState.getMonsters());
        this.repaint();
    }
    @Override
    public Directions nextMove(){
        return this.cursor.getDirection();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Labyrinth;
    private javax.swing.JTextField currentPlayerField;
    private final javax.swing.JLabel currentPlayerLabel = new javax.swing.JLabel();
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea logField;
    private final javax.swing.JLabel logLabel = new javax.swing.JLabel();
    private javax.swing.JTextArea monstersField;
    private javax.swing.JLabel monstersLabel;
    private javax.swing.JTextArea playersField;
    private final javax.swing.JLabel playersLabel = new javax.swing.JLabel();
    private javax.swing.JTextField winnerField;
    private final javax.swing.JLabel winnerLabel = new javax.swing.JLabel();
    // End of variables declaration//GEN-END:variables
}
